// GENERATED by tools/gen_content.py from content/obituary.json hobby_names. Do not edit.
// Hobby pool order is CONTRACT (SPEC 8): index = hobbyIndex(gene).
export const HOBBY_NAMES = ["fishing", "reading", "gaming", "gardening", "painting", "guitar", "lifting", "knitting", "birdwatching", "cooking", "skateboarding", "crosswords", "model trains", "coffee", "hiking", "calligraphy", "noraebang", "baduk", "beekeeping", "ham radio"];
