// GENERATED by tools/gen_content.py from content/names.json. Do not edit; edit the JSON and regenerate.
// PARITY CONTRACT (SPEC 5.5): mirrored in src/core/names_tables.h; given-name algorithm:
// PARITY CONTRACT. Algorithm and table order are mirrored in C++ and JS. Changing anything here requires regenerating test/vectors and a genome/name version bump.
// rng = Mulberry32(name_seed)
// loop:
//   parts = [ onsets[rng.range(len(onsets))] ]
//   if rng.range(4) == 0: parts.append( middles[rng.range(len(middles))] )
//   parts.append( endings[rng.range(len(endings))] )
//   name = join(parts), first letter uppercase, rest lowercase
//   if any banned substring appears in lowercase(name): continue loop (same rng, keep drawing)
//   return name
// Max length is 4 + 2 + 4 = 10 characters by construction.

export const ONSETS = [
  "Blor", "Pib", "Mox", "Glim", "Tup", "Zib", "Wob", "Dob",
  "Fen", "Gub", "Hob", "Jin", "Kip", "Lum", "Mib", "Nub",
  "Pog", "Quib", "Rux", "Snor", "Tib", "Vex", "Wim", "Yob",
  "Zor", "Bix", "Crum", "Dux", "Flib", "Grub", "Nim", "Plum",
];

export const MIDDLES = [
  "bo", "li", "ma", "ro", "zi", "ta", "nu", "pi",
  "ga", "de", "wo", "ki", "fu", "sa", "mo", "le",
];

export const ENDINGS = [
  "o", "y", "ie", "ix", "us", "el", "a", "en",
  "ers", "by", "sy", "kins", "ble", "bert", "wick", "ton",
];

export const SURNAME_SUFFIXES = [
  "ington", "sworth", "berg", "ley", "stein", "wick", "ford", "field",
  "more", "ton", "bottom", "shire",
];

export const DOUBLE_CONSONANTS = "bdgmnprt";

export const BANNED_SUBSTRINGS = [
  "ass", "fuk", "fuc", "fag", "nig", "cum", "tit", "dik",
  "dic", "sex", "kkk", "jiz", "cok", "cox", "nazi", "rape",
  "pube", "piss", "shit", "hoe", "slut", "porn", "anus", "butt",
  "dumb", "kill",
];

export const REGNAL_NUMERALS = [
  "", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
];

export const GRADES = {
  Q1: "GS-5",
  Q2: "GS-7",
  Q3: "GS-11",
  Q3_after_promotion: "GS-13",
  Q4: "GS-15",
  deceased: "GS-15 (Emeritus)",
};
