// GENERATED by tools/gen_content.py from content/rarity.json. Do not edit.
// Rarity tiers (D-091); tierOf() in js/tier.js must agree with core::genomeTier (parity test).
export const TIERS = [{"id": "common", "color": 8}, {"id": "rare", "color": 48}, {"id": "legendary", "color": 19}, {"id": "mythic", "color": 15}];
export const LEGENDARY = {"palette": [30, 31], "eyes": [7], "crest": [7]};
